### ISSUE TITLE
About jennifer view adapter lib.

### ISSUE THREAD

**Issue by minsoo-jun** [jennifersoft/jennifer-view-adapter-slack#1]
Hi.
My name is Minsoo jun.

Thank you for the Jennifer view adapter to the Open source.

By the way, I just start to make the Hipchat plugin for our the Jennifer 5.
But I can't find some lib for the Adapter plugin.
How can I find that lib?

import com.jennifersoft.view.adapter.JenniferAdapter;
import com.jennifersoft.view.adapter.JenniferModel;
import com.jennifersoft.view.adapter.model.JenniferEvent;
import com.jennifersoft.view.adapter.util.LogUtil;
 
If need to direct contact with Sales Department, Please let me know.

Best Regards.
Thank you.
minsoo

**Comment by seogi1004** [comment]
제니퍼5가 설치된 경로에 server.view/lib 디렉토리를 어댑터 프로젝트에서 라이브러리 패스만 잡아주시면 됩니다!

**Comment by minsoo-jun** [comment]
답변감사합니다.
테스트 해보겠습니다.

**Comment by minsoo-jun** [comment]
감사합니다. 무사히 플러그인 개발이 되었습니다.
