### ISSUE TITLE
슬렉 연동시 메시지가 다르게 나옴...

### ISSUE THREAD

**Issue by melong0124** [jennifersoft/jennifer-view-adapter-slack#2]
저희쪽에 뿌려지는 메시지는 이런데..
버튼 이런것도 안보이고..

![image](https://user-images.githubusercontent.com/34364366/57119347-6c447280-6da4-11e9-9f41-aa7f04f29b5f.png)

예시는 이거네요
![image](https://user-images.githubusercontent.com/3861725/49065611-d723d780-f261-11e8-98ee-8073638b9f7a.png)

현재 설정은 아래와 같이 했습니다..
![image](https://user-images.githubusercontent.com/34364366/57119372-a150c500-6da4-11e9-8ca5-bea722fe5447.png)

피드백 부탁드리겠습니다~

**Comment by abolkog** [comment]
I think you might be using an old version of the adapter. Please update to the latest one available at the [dist](https://github.com/jennifersoft/jennifer-view-adapter-slack/tree/master/dist) folder of this repo.

**Comment by melong0124** [comment]
![image](https://user-images.githubusercontent.com/34364366/57379744-78846180-71e2-11e9-9e2b-26fd1db7cc7f.png)

slack adapter 버전이 1.1.0 입니다.
jennifer server Version: 5.4.2
view server Version: 5.4.2

**Comment by seogi1004** [comment]
@melong0124 ID를 slack으로 설정해야 합니다.

**Comment by melong0124** [comment]
감사합니다. 1.1.1 버전 업그레이드 이후 해결 하였습니다.
